### ISSUE TITLE
Bring back the product website

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103-T14-3/main#99]
Guys, please bring back the product website as it might me needed for various grading purposes later.

**Comment by Oscar-B-Liang** [comment]
Hello professor, the issue about the product website has been fixed. Please check.

**Comment by damithc** [comment]
Looks like it is still showing AB3 stuff?

**Comment by Oscar-B-Liang** [comment]
Should not be, in my computer, the following link indeed links to our README file.
https://ay1920s1-cs2103-t14-3.github.io/main/

**Comment by damithc** [comment]
> Should not be, in my computer, the following link indeed links to our README file.

Oh, right. I followed this link, which you haven't updated.
![image](https://user-images.githubusercontent.com/1673303/68072507-8564c500-fdc1-11e9-920b-295aecdf2ce9.png)

Your Ui.png is still missing though.
